name: Build Kernel Zips (with/out releases)

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        default: '1.8.0'
      upload_releases:
        description: 'Upload releases'
        required: true
        default: 'true'
        type: boolean
      mark_prerelease:
        description: 'Mark as prerelease'
        required: true
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      max-parallel: 4   
      matrix:
        device: [a51,f41,m31s,m31,m21,gta4xl,gta4xlwifi]
        variant: ['', --oneui]
        ksu: ['', --no-ksu]

    name: "Build ${{ matrix.device }} ${{ matrix.variant }} ${{ matrix.ksu }}"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: apt update
        run: |
          sudo apt -y update
          sudo apt -y install bison flex libssl-dev python3 python-is-python3
          
      - name: Download clang
        run: |
          wget https://github.com/XSans0/WeebX-Clang/releases/download/WeebX-Clang-19.1.5-release/WeebX-Clang-19.1.5.tar.gz -O "weebx-clang.tar.gz"
          rm -rf toolchain && mkdir toolchain && tar -xvf weebx-clang.tar.gz -C toolchain && rm -rf weebx-clang.tar.gz

      - name: Initialize KernelSU
        if: matrix.ksu != '--no-ksu'
        run: |
          curl -LSs "https://raw.githubusercontent.com/mlm-games/KernelSU-Non-GKI/main/kernel/setup-subm.sh" | bash -s 
          python3 KernelSU/scripts/integrate-no-kprobe.py --no-defconfig-flag
      
      - uses: Wandalen/wretry.action@master
        with:
          attempt_limit: 3
          attempt_delay: 10
          command: python build_kernel.py ${{ matrix.variant }} --target=${{ matrix.device }} ${{ matrix.ksu }}

      - name: Print Logs
        if: failure()
        run: |
          find . -type f -name '*err.log' -exec cat {} \;
          
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: inputs.upload_releases == true
        with:
          files: |
            *SN*.zip
          name: SN (with/without KernelSU) Flashable zips // ${{ inputs.tag_name }}
          tag_name: ${{ inputs.tag_name }}
          body: |
            Flash using a custom recovery or Kernel Flasher from Fdroid (Gplay apps are not trustworthy for flashing)
            Open an issue with the rom and device used when it doesn't boot and you're sure it's due to the kernel.
            All are KSU zips.
            
            AOSP and OneUI variants are provided for each device.
          prerelease: ${{ inputs.mark_prerelease }}
