name: Monthly Kernel Sync

on:
  schedule:
    - cron: '0 0 1 * *'  # Run at 00:00 on the 1st of every month
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Set up branch
        run: |
          git remote add upstream https://github.com/Exynos9611Development/android_kernel_samsung_universal9611.git
          git fetch upstream
          SYNC_BRANCH="kernel-sync/$(date +%Y-%m)"
          git checkout -b $SYNC_BRANCH

      - name: Check for updates
        id: check_updates
        run: |
          git merge-base --is-ancestor upstream/main HEAD && echo "NO_CHANGES=true" >> $GITHUB_ENV || echo "NO_CHANGES=false" >> $GITHUB_ENV
          if [[ "$NO_CHANGES" == "false" ]]; then
            echo "SYNC_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
            git merge upstream/main --no-commit
            echo "CHANGES_DETECTED=true" >> $GITHUB_OUTPUT
            git diff --name-only HEAD > changed_files.txt
          fi

      - name: Create Pull Request
        if: steps.check_updates.outputs.CHANGES_DETECTED == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.SYNC_BRANCH }}
          title: "Monthly Kernel Sync: $(date +%B-%Y)"
          commit-message: |
            chore(kernel): sync with upstream kernel changes
            
            Synced with Exynos9611Development kernel repository
          body: |
            🔄 Monthly automated kernel sync
            
            This PR syncs our kernel with the latest changes from [Exynos9611Development](https://github.com/Exynos9611Development/android_kernel_samsung_universal9611).
            
            Changed files:
            ```
            $(cat changed_files.txt)
            ```
            
            This is an automated PR created by the Monthly Kernel Sync workflow.
          labels: |
            kernel-sync
            automated-pr
            needs-review

